### ISSUE TITLE
InvalidOperationException on property in Where which not specified in Select

### ISSUE THREAD

**Issue by sergey-dubovitsky** [igor-tkachev/bltoolkit#208]
Just migrated from 4.0 to 4.1.19 and now I have problems with Where clause after Select. This code 

```
using (var db = new DbManager("sql"))
{
    var filteredParentView  = db.GetTable<Parent>()
            .Where(p => p.IsDeleted == false)
            .Select(p => new ParentView { Id = p.Id, Name = p.Name });

    filteredParentView.Where(pv => pv.Childs.Any(c => c.Name == "")).ToList();
}
```

throws InvalidOperationException: Operation is not valid due to the current state of the object. If I changed new ParentView { Id = p.Id, Name = p.Name } to new ParentView { Id = p.Id, Name = p.Name, Childs = p.Childs } it throws ArgumentException Argument types do not match.

Is it possible to call additional Where after Select?

Models:

```
public class Parent {
    public int Id               { get; set; }
    public string Name          { get; set; }
    public bool IsDeleted       { get; set; }

    [Association(ThisKey="Id", OtherKey="ParentId")]
    public List<Child> Childs   { get; set; }
}

public class ParentView : Parent {
    public string ExtInfo { get; set; }
}

public class Child {
    public int Id               { get; set; }
    public int? ParentId        { get; set; }
    public string Name          { get; set; }

    [Association(ThisKey = "ParentId", OtherKey = "Id")]
    public Parent Parent        { get; set; }
}
```

**Comment by inarius** [comment]
I am hitting the second part of this issue. Why do we receive the ArgumentException? 

I.E. I can't perform the select on a relationship that contains a List<>()

    .Select(p => new ParentView { 
        Id = p.Id, 
        Name = p.Name, 
        Childs = p.Childs 
    })
