### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MajidSafari** [igor-tkachev/bltoolkit#260]
I'm using BLToolkit in my project. I run batch updates against my ms sql 2005 database using such a code:

```c#
public static int Update(List<T> entityList)
{
    return new SqlQuery<T>().Update(entityList);
}
```

but I get this error:
Index was outside the bounds of the array.

Once I changed the BLToolkit source code. There was a loop in update method in which I erased -1 in loop counter. but I think it should be right and I am making a mistake while updating my generic list.

```c#
//is true
   foreach (var memberMapper in members)
                bc.ColumnMappings.Add(new SqlBulkCopyColumnMapping(memberMapper.Ordinal - 1, memberMapper.Name));

            //has error
			//foreach (var memberMapper in members)
				//bc.ColumnMappings.Add(new SqlBulkCopyColumnMapping(memberMapper.Ordinal, memberMapper.Name));
```

**Comment by ili** [comment]
I think this is same as #279,
fixed already, more complex test done
