### ISSUE TITLE
 The timeout period elapsed prior to obtaining

### ISSUE THREAD

**Issue by MajidSafari** [igor-tkachev/bltoolkit#264]
Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.

why ?

**Comment by ili** [comment]
Yes, you can use `GetTable(true)` but i'm not sure, if it would be possible 
``` cs
var r1 = db.GetTable<A>(true).ToList();
var r2 = db.GetTable<A>(true).ToList();
```
As foe me it is much cleat to either dispose `DbManager`, or to use `DataConrext` class.
