### ISSUE TITLE
Insert a Text into Orcale longer then 2000 (4000) characters

### ISSUE THREAD

**Issue by jogibear9988** [igor-tkachev/bltoolkit#268]
I have a Orcale Database where I want to insert longer Text! I have the Problem, that I always get Exception "Zeichenfolge zu lang" wich means "String too long".

I think this a Error because the Values can only be send to Oracle using Binding instead of a String as SQL.

Does BLToolkit use Parameters or not? Any Idea how I can fix this?

My field where I want to insert this is NClob, so it's large enough!

**Comment by ili** [comment]
it looks like to be applied
