### ISSUE TITLE
TypeAccessor ignoring DefaultValueAttribute on property

### ISSUE THREAD

**Issue by Mitroz** [igor-tkachev/bltoolkit#273]
I checked unit tests for DefaultValueAttribute and only tested usage are for Enum types and after set value by object mapper. 
I would expect set default value to property after create instance by accessor or object mapper. It's bug or feature?

```
    public class ObjectWithDefaultValue
    {
        [DefaultValue(typeof(bool), true)]
        public bool Something { get; set; }
    }
    
    [TestFixture]
    public class DefaultValueFixture
    {
        [Test]
        public void DefaultValueTest()
        {
            ObjectWithDefaultValue o = TypeAccessor.CreateInstance<ObjectWithDefaultValue>();

            Assert.IsTrue(o.Something); //failed
        }
    }
```

**Comment by ili** [comment]
`DefaultValueAttribute` is used only for mapping.
There is an ability to set default property value for `abstract` classes with `ParameterAttribute`
