### ISSUE TITLE
Multiple OrderBys do not work 

### ISSUE THREAD

**Issue by jogibear9988** [igor-tkachev/bltoolkit#309]
The following Query in Bltoolkit will not work:
      
        var qry = from ss in s.Query<StorageShelfDTO>()
                    orderby ss.Id
                    select new {ss};

                qry = qry.OrderBy(x => x.ss.HostName);

                var ret = qry.ToList();

                var sql = s.LastQuery();

but I do not have a IOrderedQueryable when using Select New, so I can not Filter with ThenBy!

This can be fixed by removing

         if (!methodCall.Method.Name.StartsWith("Then"))
			sequence.SqlQuery.OrderBy.Items.Clear();

from OrderByBuilder

**Comment by jogibear9988** [comment]
In this simple example it makes maybe no sense that we don't order by both fields in the first query, but for example you have a join in the first and after that you would sort by more fields, from another function. The first query does not return a IOrderedQueryable so you can't use ThenBy and so BlToolkit will remove previous sortings...

**Comment by ili** [comment]
Generally this can be done without changing BLT, you can see commit above

**Comment by exileDev** [comment]
Also, ordering fields are duplicated independently of  `Linq.DoNotClearOrderBys` configuration value. :cry:
```
using (var db = GetDataContext(context))
{
	var firstOrder =
		from p in db.Parent
		orderby p.ParentID
		select p;

	var secondOrder =
		from p in firstOrder
		join pp in db.Parent on p.Value1 equals pp.Value1
		orderby pp.ParentID
		select p;

	var selectQuery = secondOrder.GetSelectQuery();
	Assert.That(selectQuery.OrderBy.Items.Count, Is.EqualTo(1));
}
```

SQL:
```
-- SqlServer.2008
SELECT
	[p].[ParentID],
	[p].[Value1]
FROM
	[Parent] [p]
		INNER JOIN [Parent] [pp] ON ([p].[Value1] IS NULL AND [pp].[Value1] IS NULL OR [p].[Value1] = [pp].[Value1])
ORDER BY
	[p].[ParentID],
	[pp].[ParentID]

```
