### ISSUE TITLE
Can't open online documentation

### ISSUE THREAD

**Issue by achmedzhanov** [igor-tkachev/bltoolkit#354]
http://www.bltoolkit.net/

Service Unavailable
HTTP Error 503. The service is unavailable.

**Comment by kelko** [comment]
Is the bltoolkit.net still the official page? 
When I open it in a browser I get some "GoDaddy" info that this domain was parked. So I can't access any information about this project.

**Comment by ili** [comment]
it is down for now, 

duplicates #335
