### ISSUE TITLE
One to Many association not working

### ISSUE THREAD

**Issue by Cromathaar** [igor-tkachev/bltoolkit#355]
Hi.

I have following entity classes:

public class User
{
public Int64 ID { get; set; }
public String Password { get; set; }

[Association(ThisKey="ID", OtherKey="UserID")]
public List&lt;UserSession> UserSessions { get; set; }
}

public class UserSession
{
public Int64 ID { get; set; }
public Int64 UserID { get; set;}
}

However when I try a query like that

from u in db.Users
where u.ID.Equals(some_id)
select new User
{
ID = u.ID,
Password = u.Password,
UserSessions = u.UserSessions
}

there's an exception saying about not being able to cast UserSession object to List&lt;UserSession>. For a One to One association it works alright, but for a One to Many it is not. Is it me doing something wrong or is it a bug?

**Comment by ili** [comment]
You would have `count(User) * count(UserSession)` records in source recordset (as result of `JOIN`)
because of no identity tracking in BLT it would not merge many users for sessions.

So the way is to query sessions on demand.
