### ISSUE TITLE
MemberMapper with ENumerable Types not working any more

### ISSUE THREAD

**Issue by jogibear9988** [igor-tkachev/bltoolkit#360]
With your change in SqlValueBase in fc4fdf65b7c523361645cd6d521fc9d149f44fd4 a MemberMapper like this:

      MapField(x => x.AdditionalObjects).MapIgnore(false).MemberMapper(typeof(JsonNetSerialisationMapper)).DbType(System.Data.DbType.String).Nullable();

will not work any more, because my object is IEnumerable and you will Enumerate it!

**Comment by Firebie** [comment]
Try my fix from 363

**Comment by jogibear9988** [comment]
i fixed it with https://github.com/jogibear9988/bltoolkit/commit/3ecf21764cde8bffa6b7511302fa4e938f20ce72

**Comment by ili** [comment]
Sorry for late response.
I see.... this code is needed for #344... I think it can be moved to `MappingSchema` (like it is done for another convert).
Please, can you provide the test for your case?
