### ISSUE TITLE
Invalid SQL generated after C# dll obfuscation

### ISSUE THREAD

**Issue by NikolayXHD** [igor-tkachev/bltoolkit#361]
Generated sql uses C# variable and field names in generated sql code. As a result after a dll is obfuscated, the generated SQL queries do not compile.

Example code:
public AccountUser GetAccountUser(Guid userId, Guid accountId)
{
	using (var db = createDbManager())
	{
		var result = db.GetTable<AccountUser>().FirstOrDefault(au => au.UserId == userId && au.AccountId == accountId);
			Console.WriteLine(db.LastQuery);
			return result;
	}
}

Output:
SELECT TOP (1)
        [au].[Id],
        [au].[AccountId],
        [au].[UserId]
FROM
        [Auth].[AccountUsers] [au]
WHERE
        [au].[UserId] = @p1 AND [au].[AccountId] = @accountId1

@accountId1 would change to invalid identifier after obfuscation

BlToolkit version: 4.1.21
Data provider: Sql2008DataProvider

**Comment by stsrki** [comment]
You need to define mapping attributes for your entities. For example:

    [TableName( Name = "TableName", Owner = "SchemaName" )]
    public class TableName
    {
        [MapField( "TableNameID" ), Identity( IsIdentity = true, OnInsert = true )]
        public int TableNameID { get; set; }

        [MapField( "SomeName" )]
        public string SomeName { get; set; }
    }

**Comment by ili** [comment]
please can you provide SQL query text generated after an obfuscation?
or problem is closed with @stsrki recommendations (in general they should help)
