### ISSUE TITLE
Insert fails for array field

### ISSUE THREAD

**Issue by Firebie** [igor-tkachev/bltoolkit#363]
Insert fails for class array property fields (i.e. byte[])
```cs
/*
-- Sql Server
create table TestByte
(
  data image
)
*/
  public class TestByte
  {
    public byte[] data;
  }

  using (var db = new DbManager())
  {
    db.Into(db.GetTable<TestByte>())
      .Value(i => i.data, new byte[] {1, 2, 3})
      .Insert();
  }
```

Fix:

diff --git BLToolkit.4/Data/Linq/Builder/UpdateBuilder.cs w/BLToolkit.4/Data/Linq/Builder/UpdateBuilder.cs
index 1c398fb..62cf6e4 100644
--- i/BLToolkit.4/Data/Linq/Builder/UpdateBuilder.cs
+++ w/BLToolkit.4/Data/Linq/Builder/UpdateBuilder.cs
@@ -391,7 +391,7 @@ namespace BLToolkit.Data.Linq.Builder
 				var memberAccessor = TypeAccessor.GetAccessor(member.DeclaringType)[member.Name];
 				sqlValue.SetEnumConverter(memberAccessor, builder.MappingSchema);
 			}			
-			else if (!mm.SupportsValue)
+			else if (!mm.SupportsValue && !mm.Type.IsArray)
 			{
 				sqlValue.ValueConverter = _ =>
 				{

**Comment by maxim-boligatov** [comment]
It is strange...
I just tested 3 different versions:
1) My own fork - works fine!
2) Last nuget package (4.2.0) - works fine!
3) Latest version compiled from original repository - failed!

Database Server: SQL Server 2012

**Comment by jogibear9988** [comment]
maybe same issue I have here: https://github.com/igor-tkachev/bltoolkit/issues/360
