### ISSUE TITLE
Official site doesn't work

### ISSUE THREAD

**Issue by NN---** [igor-tkachev/bltoolkit#370]
http://www.bltoolkit.net/ leads to nowhere

**Comment by kutsoff** [comment]
+1 why official site not working?

**Comment by Ubloobok** [comment]
+1 too, maybe community can help? I think complex site is not necessary, at least simple landing page will be good.

**Comment by ili** [comment]
Yes... i think that it would not be alive..
Time to migrate to https://github.com/linq2db/linq2db

**Comment by NN---** [comment]
3.5 is not supported. Cannot migrate.

**Comment by Ubloobok** [comment]
Our recent tests have shown a lot of oddities and strange errors in the linq2db.
Thanks, but while we stay at the BLToolkit.

**Comment by ili** [comment]
Really i don't think that site would be alive...
For now "on hand" i do have old wiki pages from RSDN & article for beginners, both in Russian
if someone is ready to port em on git wiki, i think it would be super
