### ISSUE TITLE
Bitmap/Image property problem/question

### ISSUE THREAD

**Issue by Ravenheart** [igor-tkachev/bltoolkit#371]
Greetings, I have a model that contains a Bitmap/Image property and BLToolkit throws an exception when it tries to .CreateInstance() that model. Specifically its the fact the Bitmap doesn't have a public constructor. Is there a way to configure BLToolkit to tell it how to build a new Bitmap/Image or how do I handle this situation?

```Could not build the 'Picture' property of the 'Joystick.BOL.Models.ModuleArt.ArtPictureModel' type: type 'System.Drawing.Bitmap' has to have public default constructor.```

**Comment by Ravenheart** [comment]
As a workaround I've made the property not-abstract and implemented INPC manually with a backing field.

**Comment by ili** [comment]
Yes, it is the way
