### ISSUE TITLE
Sql2014DataProvider.cs

### ISSUE THREAD

**Issue by MajidSafari** [igor-tkachev/bltoolkit#373]
hi i use sql2014 ,but bltoolkit useSql2008DataProvider.cs

can you add Sql2014DataProvider.cs

**Comment by ili** [comment]
In general it checks for database `compatibility_level` property and uses one of the suitable providers (2000, 2005, 2008, 2012)
For all versions higher than 2012 `Sql2012DataProvider` used.
In general there is no need of 2014 provider, if only you have some compatibility problems
