### ISSUE TITLE
InsertBatch timeout

### ISSUE THREAD

**Issue by ras254** [igor-tkachev/bltoolkit#374]
I try to call InsertBatch and sometimes get TimeoutException
I use Sql Server 2008
Is there any way to increase this timeout? (It requires the ability to change BulkCopyTimeout property at the SqlBulkCopy class)

**Comment by ili** [comment]
`SqlDataProvider.SqlBulkCopyOptions` static property can be used to set parameters you need

**Comment by ili** [comment]
Sorry, my fault, this doesn't help
