### ISSUE TITLE
SqlFunction on non static property

### ISSUE THREAD

**Issue by thtp** [igor-tkachev/bltoolkit#375]
Properties decorated with SqlFunctionAttribute should be excluded from default select expression.

```
    [TableName(Name="tbl_whatever")]
    public class Whatever
    {
        [SqlFunction("db_name", ServerSideOnly = true)]
        public string DatabaseName { get; set; }
    }
```
SQL for that class is generated like that:

```
SELECT
	[t1].[DatabaseName]
FROM
	[tbl_whatever] [t1]
```
Which is obviously incorrect.

However, it works fine for linq queries like
`.Select(x => new { DatabaseName = x.DatabaseName })`

**Comment by ili** [comment]
Not cleat why should they be excluded... 
May be  `[MapIgnore]` can help in your case?
