### ISSUE TITLE
How to implement Converter DateTime with TimeZone

### ISSUE THREAD

**Issue by b0bi79** [igor-tkachev/bltoolkit#377]
The model has a field DateTimeOffset and TimeZone. Is it possible to implement a converter that will convert DateTimeOffset to DateTime considering TimeZone?
In BLToolkit I have been implemented MemberMapper as follows:

        public override object GetValue(object o)
        {
            var dtoffset = (DateTimeOffset) base.GetValue(o);
            var pos = (PosInfo)o;
            return dtoffset > MinDate ? DateTimeHelper.ConvertToUtc(dtoffset, Tz.GetShopTimeZone(pos.shopNum)) : MinDate; 
        }

**Comment by ili** [comment]
think it goes to linq2db
