### ISSUE TITLE
Publish Oracle Managed DataProvider nuget package with updated references

### ISSUE THREAD

**Issue by pasibonfire** [igor-tkachev/bltoolkit#382]
Could you consider updating the reference of OracleManaged nuget package, as they are marked deprecated.
I would appreciate if you published Oracle Managed Data Provider as nuget a package.

**Comment by ili** [comment]
I'll try to do it ASAP

**Comment by ili** [comment]
To make clear - the deal is about migrating to this package: https://www.nuget.org/packages/Oracle.ManagedDataAccess

**Comment by ili** [comment]
New package published https://www.nuget.org/packages/BLToolkit.Oracle.Managed
