### ISSUE TITLE
Assotiation with CanBeNull after executed linq query have not null (default value) for class

### ISSUE THREAD

**Issue by Nelo-cool** [igor-tkachev/bltoolkit#387]
Hello my dear friends! Help me please.
Write this simple code:
class A
{
int Id;
[Association(CanBeNull = true, Thiskey = "Id", otherKey = "AId")]
class B b;

...
}

class B
{
int AId;
...
}

and

var query = from a in ATable
selec new 
{
a,
a.b,
}

after query.FirstOrDefault() i see, field "b" is not null but equal "new b()" with 0 in AId and other fields.

What am I doing wrong? Or this default and normal state?

**Comment by ili** [comment]
Sorry, this is by design. You do have null value columns in result dataset, so they are mapped to DefaultNullValues. This is 0 for int, for ex.

**Comment by Nelo-cool** [comment]
Thanks, but my question about class-field, example:
var query = from a in ATable
selec new
{
a,
a.b,
}

var res = query.FirstOrDefault();
Assert.IsNotNull(res.b); == > 'True', but in sql this is empty. And sql query right, include left join and other,

**Comment by Nelo-cool** [comment]
Work around:
join b in bTable into bs
from leftB in bs.DefaultIfEmpty()
select new
{
a, 
b = leftB,
}
