### ISSUE TITLE
LINQ query to BLTookit table with nullable string field

### ISSUE THREAD

**Issue by Nelo-cool** [igor-tkachev/bltoolkit#388]
Hello my diar friends:)
After execute this query:
`var query = from a in ATable
select new b
{
StringField = a.StringField
}`
In result i can see, in b.StringField value string.Empty. Why? 
I try
1. BLToolkit.Common.Configuration.NullableValues.String = null
2. Set Nullable on a.StringField
Does't work.
Can help me?

**Comment by Nelo-cool** [comment]
Oh, my problem resolved.
This string, BLToolkit.Common.Configuration.NullableValues.String = null, you must set before bltoolkit initialized by other works.

**Comment by ili** [comment]
That's cool ) 
BTW consider migration to [linq2db ](https://github.com/linq2db/linq2db/) :)

**Comment by Nelo-cool** [comment]
My legacy code with accessors... rewrite is bad idea%)
