### ISSUE TITLE
From BLToolkit DataAccessor to LINQ2DB

### ISSUE THREAD

**Issue by Nelo-cool** [igor-tkachev/bltoolkit#390]
Hello my dear friends;)
How to? Noway? Only throw away accessors and rewrite to linq all queries?
Migrate guide?

**Comment by ili** [comment]
Yes, only this way... Also no abstract types.
Guide... No guide. Generate model with t4, remove reference to toolkit, reference to linq2db, and go on

**Comment by Nelo-cool** [comment]
Thanks, now I know:) My ass is on fire.

**Comment by ili** [comment]
Sorry for bad news, my projects are now in the same case, too much dependencies on data accessors and editable objects
