### ISSUE TITLE
build BLToolkit.Annotations from BLToolkit.DataAccess

### ISSUE THREAD

**Issue by jmptrader** [igor-tkachev/bltoolkit#394]
My component with entities  (or POCO's) , I must distribute to an desktop application (winform),

But because to mapping with database the entities classes has attributes like "PrimaryKey" , then this
generates dependency with the  BLToolkit assembly by BLToolkit.DataAccess.

It possible build an BLToolkit.Annotations assembly separadly that provides an attributes classes that are used only to define metadata  (like System.ComponentModel.DataAnnotations).

Thank's for your advance,

JM

**Comment by ili** [comment]
Sorry, this would not be implemented, BLToolkit is suspended.

But! If you will implement it & make PR we can merge and release it :)
