### ISSUE TITLE
BLToolkit.Data.DataProvider.SQLite.4, Version=4.3.7.0 is not signed

### ISSUE THREAD

**Issue by WebSerGe** [igor-tkachev/bltoolkit#397]
When signed assembly tries to load installed via nuget BLToolkit.Data.DataProvider.SQLite.4, Version=4.3.7.0 then error is raised:
`Could not load file or assembly 'BLToolkit.Data.DataProvider.SQLite.4, Version=4.3.7.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)`
Manual sign of assembly with BLToolkit.snk helps to resolve the issue (disassembling/assembling with key).
Can it be fixed?

**Comment by WebSerGe** [comment]
Pull request is ready, I have never made requests, so I hope it has been done correctly.

**Comment by WebSerGe** [comment]
Link to pull request https://github.com/igor-tkachev/bltoolkit/pull/398

**Comment by WebSerGe** [comment]
While issue is opened I use such workaround to bypass run-time errors for sqlite db provider:
```
  <Target Name="BeforeBuild">
    <Exec ContinueOnError="false" Command="..\..\packages\Brutal.Dev.StrongNameSigner.2.1.0\build\StrongNameSigner.Console.exe -in &quot;..\..\packages\BLToolkit.SQLite.4.3.7\lib\net40|..\..\packages\BLToolkit.4.3.7\lib\net40|..\..\packages\System.Data.SQLite.Core.1.0.105.0\lib\net40&quot; -k BLToolkit.snk" />
  </Target>
```
Not the best option because it is not generic but will be changed if future releases of database providers will not be strong-named assemblies.

**Comment by ili** [comment]
Thanks!
Now all assemblies are signed, version 4.3.8 published :)
